### PR TITLE
Travis: Use stable releases of Rubies

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR only updates the CI matrix to the latest generally available Ruby versions.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@senny It seems that PR builds are not enabled for this Travis project.

**Comment by olleolleolle** [comment]
The current installation issues are about:

```
Gem::InstallError: nio4r requires Ruby version >= 2.2.2.
Gem::InstallError: rack requires Ruby version >= 2.2.2.
An error occurred while installing nio4r (2.0.0), and Bundler cannot continue.
```

**Comment by senny** [comment]
As I was only working on queue_classic proper, I don't have any knowledge of this projects setup.

@olleolleolle the previous PR's seemed easy enough to give a green light. I'll leave this one open to maintainers that have worked on `queue_classic_admin`. From the commit history it looks like there hasn't been much activity lately. Do you intend to add specific features? Maybe sync quickly with @jipiboily on what's the latest state on this project.

**Comment by olleolleolle** [comment]
@senny I just want it to be able to run its tests green, being a good neighbour.

**Pull request merged**
