### PR TITLE
Allow users to specify custom actions for all matching jobs

### PR DESCRIPTION
**Pull request by paul**
Works similarly to the custom action for a single job implementation.

### CODE REVIEW

**Comment by jipiboily** [comment]
:heart:
Failed build though... :grinning:

**Comment by paul** [comment]
```

ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR: type "json" 
does not exist

LINE 1: ...me" text NOT NULL, "method" text NOT NULL, "args" json NOT N...

  ```

Only fails on Ruby 2.0.0, 2.1.2 passes. Seems like that might be also an 
older version of PG?

> Jean-Philippe Boily <mailto:notifications@github.com>
> January 6, 2015 at 7:45 PM
>
> :heart:
> Failed build though... :grinning:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/QueueClassic/queue_classic_admin/pull/32#issuecomment-68971699>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by jipiboily** [comment]
Weird...unlikely to fix it but I would restart the build (I'm on my phone)...

Feels like an old version of pg...but it should be on same version in theory...

**Comment by paul** [comment]
Yeah, I restarted it twice already.

> Jean-Philippe Boily <mailto:notifications@github.com>
> January 6, 2015 at 8:48 PM
>
> Weird...unlikely to fix it but I would restart the build (I'm on my 
> phone)...
>
> Feels like an old version of pg...but it should be on same version in 
> theory...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/QueueClassic/queue_classic_admin/pull/32#issuecomment-68975494>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by paul** [comment]
It seems like travis is using the wrong version of pg for the ruby 2.0.0 build. I've sent an email to support.

**Comment by jipiboily** [comment]
Seems unrelated to this PR, so I would personally merge it.

**Pull request merged**
